### PR TITLE
15 story weburl

### LINKED ISSUE #15: Story can take a webUrl
requires a storyUrl component

### PR DESCRIPTION
**Pull request by RSijelmass**
Closes #15

### CODE REVIEW

**Review by bannastre — CHANGES_REQUESTED** [review]
please remove .js.swo(p) files from our beautiful repo

**Review by bannastre — DISMISSED** [review]
:shipit:

**Comment by RSijelmass** [comment]
Removed swap files, merged because of conflict

**Review by bannastre — APPROVED** [review]
:shipit:

**Pull request merged**
